version: '3'

services:
  app:
    container_name: cura
    restart: always
    build: .
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_LOCAL=mongodb://localhost:27017/cura
      - DATABASE=mongodb://mongo:27017/cura
    ports:
      - "80:3000"
    links:
      - mongo
      - mongo-express
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
        - mongo
    ports:
      - 8081:8081