version: '3'

services:
  app:
    container_name: cura
    restart: always
    build: .
    environment:
      - DATABASE_MONGO=mongodb://mongo:27019/cura
    ports:
      - "80:3000"
    links:
      - mongo
      - mongo-express
  mongo:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=est1234
    ports:
      - 27017:27017
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=test1234
      - ME_CONFIG_MONGODB_SERVER=mongo